version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    target-branch: main
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: main
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: main
    schedule:
      interval: "daily"
